name: Universal CI

on:
  pull_request:
  push:
    branches: [$default-branch]
    tags: ['**']
  workflow_dispatch:

permissions:
  contents: read

jobs:
  universal:
    uses: Intuitumxyz/.github/.github/workflows/universal-ci.yml@main
